name: build-specific-version
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Which Image Tag to Build?
        required: true
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mjdazz/nextcloud-ocrmypdf:${{ github.event.inputs.version }}
          build-args: |
            VERSION=${{ github.event.inputs.version }}
