name: build-docker-image-on-demand
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Nextcloud Version to build"
        required: true
        type: string
jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["${{ inputs.version }}",
                  "${{ inputs.version }}-apache",
                  "${{ inputs.version }}-fpm",
                  "latest",
                  "apache",
                  "fpm",
                  "latest",
                  "production",
                  "production-apache",
                  "production-fpm",
                  "stable",
                  "stable-apache",
                  "stable-fpm",
                  ]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mjdazz/nextcloud-ocrmypdf:${{ matrix.version }}
          build-args: |
            VERSION=${{ matrix.version }}
